### PR TITLE
Updated to pull in the page layout required attribute. 

### PR DESCRIPTION
**Pull request by timbarsotti**
Updated readme with dynamic field list, additional setting requirements, and how to use required in the example.

### CODE REVIEW

**Comment by anyei** [comment]
@timbarsotti  Good catch on the "required" attribute, I like it. Someone else already added lines in the readme file for the following:
List<String> fields = new List<String>{'Id', 'AccountNumber', 'AccountSource', 'AnnualRevenue', 'BillingAddress', 'BillingCity', 'BillingCountry',
									  'BillingGeocodeAccuracy', 'BillingLatitude', 'BillingLongitude', 'BillingPostalCode', 'BillingState', 'BillingStreet',
									  'CleanStatus', 'CreatedById', 'CreatedDate', 'DandbCompanyId', 'Description', 'DunsNumber', 'Fax', 'Industry', 'IsDeleted',
									  'Jigsaw', 'JigsawCompanyId', 'LastActivityDate', 'LastModifiedById', 'LastModifiedDate', 'LastReferencedDate', 'LastViewedDate',
									  'MasterRecordId', 'NaicsCode', 'NaicsDesc', 'Name', 'NumberOfEmployees', 'OwnerId', 'Ownership', 'ParentId', 'Phone', 'PhotoUrl',
									  'Rating', 'ShippingAddress', 'ShippingCity', 'ShippingCountry', 'ShippingGeocodeAccuracy', 'ShippingLatitude', 'ShippingLongitude',
									  'ShippingPostalCode', 'ShippingState', 'ShippingStreet', 'Sic', 'SicDesc', 'Site', 'SystemModstamp', 'TickerSymbol', 'Tradestyle',
									  'Type', 'Website', 'YearStarted', 'OwnerId'};
controller.addFields(fields);


Can you pull the latest readme file and do your changes on top of it so that you don't have to add the portion of the code to add the fields....

**Review by anyei — COMMENTED** [review]
This is great man thanks @timbarsotti !..

I only have one request... can you get the latest readme file first and then do the changes on it... i believe you worked on an old version of the readme file. 
Besides that this looks really good man thanks.

**Comment by timbarsotti** [comment]
Hi! I purposefully removed the statically typed fields and added a snippet to dynamically pull in all fields for the record - So if you add a new field to the object / page layout, no recoding will be required. 

+	/* dynamically get all fields for the Account object and add them to the controller */
 +    List<String> fieldList = new List<String>();
 +    for(Schema.SObjectField field: Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().values()) {
        fieldList.add(String.ValueOf(field));
   }

**Review by anyei — COMMENTED** [review]
@timbarsotti  I see, can you check if you can actually put ALL fields to the controller... I have not confirmed it yet but stuff like "Id" which is already loaded by default by the controller will potentially fail, so you might need to skip some standard fields i guess...

**Comment by timbarsotti** [comment]
Hi @anyei confirmed - it works pulling all fields.

**Review by anyei — APPROVED** [review]
@timbarsotti  Thanks very much!!!

**Pull request merged**
